### ISSUE TITLE
Help message box issue - windows

### ISSUE THREAD

**Issue by nitawa** [SalomePlatform/mmgplugin#28]
the current implementation seem
a suggested solution is to replace None by self such that the help windows 
https://github.com/SalomePlatform/mmgplugin/blob/d56ecf95a303d7e35070a1cd2f94b404bb91437e/myMmgPlugDialog.py#L347

**Comment by mohd-afeef-badri** [comment]
@nitawa sorry I do not really understand the issue. Is it that on on Windows OS the "Help" does not show up ? and the proposed solution is to replace `None` by `self` ? Sorry again if the question is too basic

**Comment by mohd-afeef-badri** [comment]
@nitawa I checked the latest archive on UB22.04 with `QMessageBox.about(None, ....` and `QMessageBox.about(self, ....` and I confirm that  both remain stable, no freezing. Since this argument is more got to do with the positioning of the widget in this case, we can surely move to `self` if it helps windows.
